services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - '0.0.0.0:3000:3000'
    restart: unless-stopped
    develop:
      watch:
        - path: ./src
          action: sync+restart
          target: /app/src
        - path: packages.json
          action: rebuild
    depends_on:
      - redis
      - mongodb
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URL=mongodb://development:development@mongodb:27017/development

  redis:
    image: redis:7.4
    restart: always
    attach: false
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis-data:/data:rw

  mongodb:
    image: mongo:8.0
    restart: always
    attach: false
    ports:
      - '127.0.0.1:27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: as67f5as8765a
      MONGO_INITDB_DATABASE: development
    volumes:
      - mongodb-data:/data/db:rw
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  redis-data:
  mongodb-data:
